"""
Slot Join Service -- user-facing "join a tournament slot" flow for
recurring-schedule tournaments (Free Fire Clash Squad style 1v1/2v2/3v3/4v4
and solo battle-royale slots).

Match-refactor: a "slot" is now a plain `Tournament` row (generated by
SlotGeneratorService) rather than a `Match` under a parent Tournament.
Two join paths:

- SOLO: charge the entry fee and create a `TournamentParticipant` row
  directly against the slot Tournament.
- TEAM (Clash-Squad-style): CREATE a new `TournamentTeam` for this slot
  and share the invite code, INVITE a friend's `TournamentTeam` via
  their invite code, or RANDOM matchmaking into (or start) a
  `TournamentTeam` flagged is_random=True. Once the team is full, a
  single `TournamentParticipant` row is created pointing at the team.
"""
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import ConflictException, NotFoundException, ValidationException
from app.models.game_profile import UserGameProfile
from app.models.tournament import Tournament, TournamentStatus
from app.models.tournament_participant import (
    TournamentAssignmentType,
    TournamentCheckInStatus,
    TournamentParticipant,
)
from app.models.tournament_team import TournamentTeam, TournamentTeamMember, TournamentTeamStatus
from app.models.team import generate_team_name
from app.models.user import User
from app.repositories.base import BaseRepository
from app.repositories.tournament_participant_repository import TournamentParticipantRepository
from app.repositories.tournament_repository import TournamentRepository
from app.repositories.tournament_team_repository import TournamentTeamRepository
from app.repositories.participant_repository import ParticipantRepository
from app.services.wallet_service import WalletService

_WALLET_SLOT_ENTRY_REF_TYPE = "tournament_slot_entry_fee"

_TEAM_SIZE_BY_FORMAT = {"solo": 1, "1v1": 1, "2v2": 2, "3v3": 3, "4v4": 4}


class SlotJoinService:
    def __init__(self, session: AsyncSession) -> None:
        self.session = session
        self.tournament_repo = TournamentRepository(session)
        self.slot_repo = TournamentParticipantRepository(session)
        self.tournament_team_repo = TournamentTeamRepository(session)
        self.participant_repo = ParticipantRepository(session)
        self.wallet_service = WalletService(session)

    async def _get_joinable_slot(self, tournament_id: UUID) -> Tournament:
        tournament = await self.tournament_repo.get_by_id(tournament_id)
        if tournament is None:
            raise NotFoundException("Tournament slot not found")
        if tournament.status != TournamentStatus.SCHEDULED:
            raise ValidationException(
                f"This slot is no longer open to join (status: {tournament.status.value})"
            )
        return tournament

    async def _assert_capacity(self, tournament: Tournament) -> None:
        current = await self.slot_repo.count_for_match(tournament.id)
        if current >= tournament.max_players:
            raise ConflictException("This slot has reached maximum capacity")

    async def _charge_entry_fee(self, tournament: Tournament, user: User, fee) -> None:
        if not fee or fee <= 0:
            return
        await self.wallet_service.debit(
            user,
            amount=fee,
            reference_type=_WALLET_SLOT_ENTRY_REF_TYPE,
            reference_id=str(tournament.id),
            description=f"Entry fee for '{tournament.title}'",
            commit=False,
        )

    # ------------------------------------------------------------------
    # Solo join
    # ------------------------------------------------------------------
    async def join_solo(
        self, tournament_id: UUID, current_user: User, game_profile: UserGameProfile
    ) -> TournamentParticipant:
        tournament = await self._get_joinable_slot(tournament_id)
        await self._assert_capacity(tournament)

        existing_participant = await self.participant_repo.get_by_tournament_and_user(
            tournament.id, current_user.id
        )
        if existing_participant is not None:
            already = await self.slot_repo.get_by_match_and_participant(
                tournament.id, existing_participant.id
            )
            if already is not None:
                raise ConflictException("You have already joined this slot")

        from app.models.participant import Participant, ParticipantPaymentStatus, ParticipantStatus

        await self._charge_entry_fee(tournament, current_user, tournament.entry_fee)

        participant = existing_participant or await self.participant_repo.create(
            tournament_id=tournament.id,
            user_id=current_user.id,
            game_profile_id=game_profile.id,
            status=ParticipantStatus.CONFIRMED,
            payment_status=ParticipantPaymentStatus.PAID,
            entry_fee_paid=tournament.entry_fee,
        )

        slot_number = await self.slot_repo.next_slot_number(tournament.id)
        slot = await self.slot_repo.create(
            tournament_id=tournament.id,
            participant_id=participant.id,
            slot_number=slot_number,
            assignment_type=TournamentAssignmentType.REGISTERED,
            check_in_status=TournamentCheckInStatus.NOT_OPEN,
        )
        await self.tournament_repo.update(
            tournament, current_players=tournament.current_players + 1
        )
        await self.session.commit()
        await self.session.refresh(slot)
        return slot

    # ------------------------------------------------------------------
    # Team join (Clash-Squad-style)
    # ------------------------------------------------------------------
    async def _assert_team_slot_has_room(
        self, tournament: Tournament, team_size: int
    ) -> None:
        active_teams = await self.tournament_team_repo.count_teams_for_match(tournament.id)
        max_teams = tournament.max_players // team_size if team_size else tournament.max_players
        if active_teams >= max_teams:
            raise ConflictException("This slot has reached maximum team capacity")

    async def join_team(
        self,
        tournament_id: UUID,
        current_user: User,
        game_profile: UserGameProfile,
        team_format: Optional[str],
        invite_code: Optional[str],
        join_random: bool,
    ) -> TournamentTeam:
        tournament = await self._get_joinable_slot(tournament_id)

        resolved_format = team_format or (
            "solo" if tournament.category is None or tournament.category.value == "solo"
            else f"{tournament.squad_size}v{tournament.squad_size}"
        )
        team_size = _TEAM_SIZE_BY_FORMAT.get(resolved_format)
        if team_size is None:
            raise ValidationException(f"Unrecognized team_format '{resolved_format}'")

        if invite_code:
            tournament_team = await self.tournament_team_repo.get_by_invite_code(invite_code)
            if tournament_team is None or tournament_team.tournament_id != tournament.id:
                raise NotFoundException("Invalid invite code for this slot")
            if tournament_team.status != TournamentTeamStatus.FORMING:
                raise ValidationException("This team is no longer accepting members")
            if tournament_team.current_members >= tournament_team.team_size:
                raise ConflictException("This team is already full")
        elif join_random:
            tournament_team = await self.tournament_team_repo.find_open_random_team(tournament.id)
            if tournament_team is None:
                await self._assert_team_slot_has_room(tournament, team_size)
                tournament_team = await self.tournament_team_repo.create(
                    tournament_id=tournament.id,
                    team_name=generate_team_name(),
                    captain_id=current_user.id,
                    team_format=resolved_format,
                    team_size=team_size,
                    current_members=0,
                    is_random=True,
                    status=TournamentTeamStatus.FORMING,
                )
        else:
            await self._assert_team_slot_has_room(tournament, team_size)
            tournament_team = await self.tournament_team_repo.create(
                tournament_id=tournament.id,
                team_name=generate_team_name(),
                captain_id=current_user.id,
                team_format=resolved_format,
                team_size=team_size,
                current_members=0,
                is_random=False,
                status=TournamentTeamStatus.FORMING,
            )

        await self._charge_entry_fee(tournament, current_user, tournament.entry_fee)

        member_repo = BaseRepository(self.session, TournamentTeamMember)
        await member_repo.create(
            tournament_team_id=tournament_team.id, user_id=current_user.id
        )

        # Mirror a Participant row for this membership so "my registrations" /
        # "my teams" (GET /tournaments/{id}/registration) and payment/check-in
        # flows see this join, exactly as the solo path does above.
        from app.models.participant import (
            ParticipantPaymentStatus,
            ParticipantStatus,
            RegistrationType,
        )

        existing_participant = await self.participant_repo.get_by_tournament_and_user(
            tournament.id, current_user.id
        )
        payment_status = (
            ParticipantPaymentStatus.PAID
            if tournament.entry_fee and tournament.entry_fee > 0
            else ParticipantPaymentStatus.NOT_REQUIRED
        )
        if existing_participant is None:
            await self.participant_repo.create(
                tournament_id=tournament.id,
                user_id=current_user.id,
                game_profile_id=game_profile.id,
                registration_type=RegistrationType.TEAM,
                team_name=tournament_team.team_name,
                status=ParticipantStatus.CONFIRMED,
                payment_status=payment_status,
                entry_fee_paid=tournament.entry_fee if payment_status == ParticipantPaymentStatus.PAID else 0,
            )
        else:
            await self.participant_repo.update(
                existing_participant,
                game_profile_id=game_profile.id,
                registration_type=RegistrationType.TEAM,
                team_name=tournament_team.team_name,
                status=ParticipantStatus.CONFIRMED,
                payment_status=payment_status,
                entry_fee_paid=tournament.entry_fee if payment_status == ParticipantPaymentStatus.PAID else 0,
                cancelled_at=None,
                joined_at=datetime.now(timezone.utc),
            )

        new_count = tournament_team.current_members + 1
        team_full = new_count >= tournament_team.team_size
        tournament_team = await self.tournament_team_repo.update(
            tournament_team,
            current_members=new_count,
            status=TournamentTeamStatus.LOCKED if team_full else TournamentTeamStatus.FORMING,
        )

        if team_full:
            slot_number = await self.slot_repo.next_slot_number(tournament.id)
            await self.slot_repo.create(
                tournament_id=tournament.id,
                tournament_team_id=tournament_team.id,
                slot_number=slot_number,
                assignment_type=(
                    TournamentAssignmentType.RANDOM
                    if tournament_team.is_random
                    else TournamentAssignmentType.REGISTERED
                ),
                check_in_status=TournamentCheckInStatus.NOT_OPEN,
            )
            await self.tournament_repo.update(
                tournament, current_players=tournament.current_players + 1
            )

        await self.session.commit()
        await self.session.refresh(tournament_team)
        return tournament_team